### ISSUE TITLE
Should `cyclone-winds` have a lock mechanism?

### ISSUE THREAD

**Issue by arthurmaciel** [cyclone-scheme/winds#11]
@justinethier, what do you think? Should we lock the package repository on the system when trying to write to it?

**Comment by justinethier** [comment]
That's not a bad idea and other package managers do this. Perhaps we could write a lock file or such to the file system while a package modification is in progress.

I do suggest as a failsafe we clear any locks as part of our install and/or uninstall of cyclone-winds.

**Comment by justinethier** [comment]
Point of reference, when `apt` detects another lock it will display a path to the lock file. This might be a good idea for `cyclone-winds` to improve a user's troubleshooting ability in exceptional cases:

    # apt upgrade
    E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by arthurmaciel** [comment]
Thanks for that, @justinethier! Corrected that on 1b6e413b6aec6bd0f41b52c33c71cb14803b7a85.
