### ISSUE TITLE
Update packages documentation

### ISSUE THREAD

**Issue by arthurmaciel** [cyclone-scheme/winds#16]
@justinethier, the wiki automation is already working, but it has some limitations:

- github replaces "-" on package names so "array-list" becomes "array list" on some places
- the automation system strictly imports data from `README.md` inside each package repo and no other doc format is allowed
- it needs better formatting - any suggestions are welcome :)

The wiki page of each package will be updated according to changes on `README.md` of each package and consequent updates on `index.scm` or any other file pushed on `cyclone-winds` repo.

If you have any ideas to improve it, please let me know. 

[Iset page](https://github.com/cyclone-scheme/cyclone-winds/wiki/iset) is the model to new packages added with `package.scm` and `README.md` produced by the command `cyclone-winds package[-srfi]` . 

All other wikis that already contained some manual documentation were not modified. Empty wiki lists before now have an automatic content (in fact a bit wrong due to some experiments), but they will be corrected as soon as the `README.md` files of those packages are created/updated by their maintainers (in this case us :).

If you don't have time to update your packages, please let me know that I will do it.

**Comment by arthurmaciel** [comment]
@justinethier, another point: if Cyclone Winds will accept packages not hosted on cyclone-scheme repo, I think we should include a `(source ...)` parameter on `package.scm`, don't you think? So we could automatically put the link to the source code in new wiki generated. Thoughts for the near future.

**Comment by justinethier** [comment]
@arthurmaciel This is great! Let me make a pass and update the docs on the packages I put together, and I will look over your changes in the process.

One immediate concern/question - I updated the docs for curl and sha2 and pushed an update to cyclone-winds. But I do not see the linked wiki pages update (EG: https://github.com/cyclone-scheme/cyclone-winds/wiki/sha2 ). Am I missing something?

**Comment by justinethier** [comment]
@arthurmaciel My bad, realized that everything is pulled from the release rather than directly from the repo. Let me package up new releases...

**Comment by arthurmaciel** [comment]
Yes, @justinethier. It is kind of cumbersome to create new releases and update the sha256 on `index.scm`, but I can't think of a more secure way at the moment. We could in the future do as snow-fort.org and let each maintainer sign her/his packages, but a secure mechanism would be needed anyway. If you have any other suggestions, please let me know :)

**Comment by justinethier** [comment]
@arthurmaciel agree but it works well for now. Will definitely let you know if any ideas come to mind.

**Comment by arthurmaciel** [comment]
Great, @justinethier! It was not clear to me, but do you find useful a `(source ...)` parameter on `package.scm` to track new packages hosted outside the `cyclone-scheme` repo? I would make `cyclone-winds package[-srfi]` to generate this tag with a default value pointing to our repo and the user can change it if it is not the case. 

It is boring to make a release every time we decide on a new feature, but I think only now we are discovering the real needs of our system.

I was also wondering about a security policy for packages hosted outside our repo. When someone sends a PR to subscribe her/his package in `index.scm` we could take a look at `package.scm` and then at the `(source ...)` to guarantee no clear bug or harm is involved.

If you agree, I will write on `cyclone-winds` docs about this procedure of adding "foreign" packages.

**Comment by arthurmaciel** [comment]
Oh, other two points are if we:

1)  should make mandatory a `README.md` *or* we should give the possibility of updating the wiki with the link pointed by the `(docs ...)` parameter in `package.scm` (if the docs are in another page);

2) should make tests mandatory.

About (1) I think we should enforce a `README.md` in the package repo because `cyclone-winds package[-srfi]` already produces a decent one. And in that file the package author could place a link to existing documentation elsewhere if she/he already has one.

About (2) I don't have a clear opinion. To make tests mandatory could raise the level of quality of code provided, but we know writing good and effective tests is an art. Should `cyclone-winds package[-srfi]` also provides a test stub now that we have access to all procedures definitions of a package? Maybe with a `test-assert`, `test-error` and `test` stub call for each of the procedure definitions?

**Comment by arthurmaciel** [comment]
Thanks, @justinethier!
