### ISSUE TITLE
Package adding policy

### ISSUE THREAD

**Issue by arthurmaciel** [cyclone-scheme/winds#17]
@justinethier, I will write on `cyclone-winds` docs about some 'policy' for writing packages hosted on the `cyclone-scheme` repo and also self-hosted elsewhere.

1) I think we need a `(source ...)` parameter on `package.scm` to track new packages hosted outside the `cyclone-scheme` repo. I could make `cyclone-winds package[-srfi]` to generate this tag with a default value pointing to our repo and the user can change it if needed. Do you agree?

2) What I thought about a security policy for adding packages: when someone sends a PR to subscribe her/his package in `index.scm`, the contributors from the community should revise `package.scm` and then the link pointed by `(source ...)` to guarantee no clear bug or harm is present. Does it make sense to you? Of course feel free to say if it is too early to define a policy like this.

About package authoring there are other two important points I would like to discuss:

3)  if we should make mandatory a `README.md` *or*, if the package author already has docs in another page, if we should give the possibility of updating the wiki *only* with the link pointed by the `(docs ...)` parameter in `package.scm`.

IMHO we should enforce a `README.md` in the package repo because `cyclone-winds package[-srfi]` already produces a decent one. And in that file the package author could place a link to existing documentation elsewhere if she/he already has one.

4) if we should make tests mandatory.

I don't have a clear opinion on that. To make tests mandatory could raise quality of provided code, but we know writing good and effective tests is an art. Should `cyclone-winds package[-srfi]` also provide a test stub, now that we have access to all procedures definitions of a package? Maybe with stub calls for `test-assert`, `test-error` and `test`  for each of the exported procedures? I think this is a good idea.

When we define what is mandatory I will provide two new commands: `cyclone-winds package-ready [DIR]` and `cyclone-winds remote-package-ready TARBALL-URL`. They would check if everything is ok (if `package.scm` is valid, if `README.md` is present, if `cyclone-winds build-local` works and if `cyclone-winds test-local` passes). This would involve a great effort to make things smoother, but, after that, the 

package author would only:

1) write code
2) run `cyclone-winds package[-srfi]`
3) adapt `package.scm`
4) adapt `README.md`
5) adapt `tests.scm`
4) run `cyclone-winds package-ready` [if errors, go back to 1, 3, 4 or 5]
5) if ok, send a PR to subscribe her/his package on `index.scm`

And code reviewer would only:
1) inspect `package.scm` (pointed in the PR on `index.scm`)
2) inspect code pointed by `(source ...)` in `package.scm`
3) run `cyclone-winds remote-package-ready _tarball-url_` (pointed in the PR on `index.scm`)
4) if ok, approve the PR on `index.scm`.

Long message, but your opinion will be very helpful.

**Comment by justinethier** [comment]
My initial thoughts:

1. Sounds good. Ideally it would not be necessary to use `(source ...)` as all of the assets pointed to by our index would be within the repo, but there is nothing explicitly enforcing that.
2. Agree it would be a good idea to do a review of these items prior to accepting a package.
3. Could we do both? IE, use the `README.md` if it is present but if not then attempt to use the `(docs ...)` link.
4. Interesting. I like the idea of providing stubs though this could be tricky for certain libraries (EG: what about macros, variables, etc?). I suppose the user can always delete the stubs if they have a more appropriate set of tests; but we can at least point them in the right direction and encourage writing tests.

Hope that helps @arthurmaciel

**Comment by arthurmaciel** [comment]
@justinethier, it helps a lot!

With regard to point (1), I realized no `(source ...)` is needed as we can use the URL of `package.scm` provided in `index.scm`, just removing the `package.scm` part. I can't see a reason why the `package.scm` file would be published outside the source code directory.

I agree with all the rest! Thanks!
