### ISSUE TITLE
Is the (cyclone ...) prefix mandatory for packages?

### ISSUE THREAD

**Issue by arthurmaciel** [cyclone-scheme/winds#29]
@justinethier, to plan ahead, is the `(cyclone ...)` prefix mandatory for packages? Or can package authors provide libraries unprefixed like `(my-lib)` , `(message-pack)`, etc?

**Comment by justinethier** [comment]
That's a good question @arthurmaciel 

I would say we do want a `cyclone` prefix in order to keep everything organized, and recommend unprefixed libraries for use as internal application-level libraries used directly by programs. For example, how the libraries are organized for winds.

**Comment by arthurmaciel** [comment]
Thanks, @justinethier!
