### ISSUE TITLE
Should Winds install packages localy by default?

### ISSUE THREAD

**Issue by arthurmaciel** [cyclone-scheme/winds#31]
@justinethier, I think I could extend Winds to manage not only packages, but Cyclone projects too. The idea is that a project may have Winds packages installed on its own directory, along with a `project.scm` file that would contain a list of package dependencies and maybe a recipe to build the whole project.

If you find that a good idea, what do you think of changing  Winds to install _by default_ packages into a folder like `winds` or `cyclone_modules` in the current directory? This is the Node.js/npm approach to install libraries into `node_modules`.

To install packages globally some flag should be passed onto the `winds install` command (e.g. `winds install -g ...`). Of course this would produce changes to Cyclone itself, to check for libraries first at `winds`, then at `/usr/local/...`. 

Another option is to port something like Python's virtualenv tool (I am also working on it), which would change `CYCLONE_LIBRARY_PATH` env var when someone wants to create a project. Winds would deal with the creation of the 
`project.scm` file itself.

I can't decide at the moment which solution would be more elegant, safer and sustainable for Cyclone users. Could you give your opinion on that please?

**Comment by arthurmaciel** [comment]
After a second thought, I realized that for basic purposes `package.scm` works fine for local project management. One can define the project dependencies in the package file and use `winds build-local` to compile (and test) the project. 

Despite this conclusion, I am still wondering if Winds default behaviour should be to install locally or globally... At the moment I think the virtual-env solution has more advantages, for instance creating a symlink for a specific compiler version used by the project. So a project created with this tool could be very encapsulated, by "freezing" as many variables as possible.

**Comment by justinethier** [comment]
I like the idea of being able to install local packages. I think this will work out of the box if we create subdirectories in the current directory; most everything would be under `cyclone` though there might be some `srfi` folders as well. Not as clean as using `cyclone-modules` though that would require changes to cyclone in order to automatically recognize the imports.

I'm a little fuzzy on how the virtual-env solution compares to a local installation. Could you provide more information for a comparison?

**Comment by arthurmaciel** [comment]
@justinethier, here is an [edited] excerpt from [Chicken's `cenv`](https://github.com/ursetto/cenv):

> # cenv
>
> Chicken 5 virtual environments.
>
> ## Description
>
> A single script, `cenv.scm`, which creates a self-contained Chicken 5 environment in a specified directory. It remembers which  Chicken you used to create it, and it keeps its own repository of eggs, which extends Chicken's default repository.
>
> When the environment is active, `csi` and `csc` and compiled programs use this repository, falling back to the default repository if an extension does not exist. `chicken-install` installs eggs into this new repository. `chicken-uninstall` is also limited to the new repository, and `chicken-status` shows both, the local and the default (global) repositories. 
>
>`cenv` could be useful if:
>
>- You are a regular user using the system Chicken and you have no permissions to, or don't want to, install eggs system-wide.
>- You want to test or switch between different versions of eggs, without creating an entire Chicken installation to house them.

So virtual environments are used for really self-contained local installations/projects, not messing with the default package repositories, nor with other local installations/projects.

The usage is simple (edited):
```
$ cenv init <directory>
$ source <directory>/bin/cenv-enter
```
And then inside this directory one can use `chicken-install ...` and all installed packages will be inside `<directory>/lib/`. At the end, one just leaves the virtual env with:
```
$ exit
```
 
The main goal is achieved by changing, in our case, `CYCLONE_LIBRARY_PATH` to `<directory>/lib/`, so all package installation while inside a virtual environment occurs in that directory.

**Comment by arthurmaciel** [comment]
At the moment we will let local installation be made through the `CYCLONE_LIBRARY_PATH` env var or through a `venv`-like package.
