### ISSUE TITLE
Upgrade command

### ISSUE THREAD

**Issue by justinethier** [cyclone-scheme/winds#4]
At some point it would be helpful to have an upgrade command to install the latest version of each installed package.

**Comment by justinethier** [comment]
The syntax of the command can be:

    upgrade [PACKAGE ...]

So we effectively:

- Check given packages to see if a newer remote version is available. 
- If no packages are given, check all installed packages

If any newer version is found on the remote server that new version of the package will be installed. 

I suggest we also check cyclone version as well, and treat it in the same manner as package version. This allows a seamless upgrade after installing a new version of Cyclone. 

Note there may be some issues with dependency trees. We need to take care of any package dependencies first, before the packages that depend on them. Otherwise we run the risk of having a package build fail due to a missing/incomplete/out-of-date dependency.

**Comment by justinethier** [comment]
Added `upgrade` per above spec. Note this is actually a very simple variation on `install` where we build a list of packages from the local index, if none is specified. @arthurmaciel already did all the hard work :)

**Comment by arthurmaciel** [comment]
Cyclone-winds is much more robust now that you've implemented all these new functionalities, @justinethier! The Cyclone community really appreciate it! :)

**Comment by justinethier** [comment]
You're welcome @arthurmaciel ! 

This project is looking really good :). I am going to work at adding a few more packages and will see if there is anything that needs to be ironed out. My tentative plan is to do an official release later on in April, including adding winds to the cyclone-bootstrap release.

**Comment by arthurmaciel** [comment]
Hurray!! I have a special winds package coming soon! It is a simple FastCGI web framework to work with any standard web server (tested on Apache). It is already working but on bare bones. I am going to finish it so we can celebrate cyclone-winds official release into cyclone-bootstrap with more new packages!

**Comment by justinethier** [comment]
Sounds great @arthurmaciel ! Looking forward to it :)
