### ISSUE TITLE
Do not download/reinstall package if it is already installed

### ISSUE THREAD

**Issue by justinethier** [cyclone-scheme/winds#5]
If a package is already installed, an install command should recognize that and not install the package again if it is a dependency.

**Comment by arthurmaciel** [comment]
Just a note: check cyc-version. Ask user to authorize update if dependency is already installed but compiled with older Cyclone version?

**Comment by justinethier** [comment]
@arthurmaciel good question. I think we want to go ahead and reinstall if the package is compiled with an older version, to avoid the possibility of breaking changes between Cyclone versions.

**Comment by justinethier** [comment]
@arthurmaciel This change has been made as well as adding a `reinstall` command to do an unconditional build&install. I have found reinstall useful occasionally with other packaging systems such as `yum`.

Please let me know your thoughts.

**Comment by arthurmaciel** [comment]
Awesome, @justinethier! Thanks!
