### ISSUE TITLE
Record cyclone version used to install a package

### ISSUE THREAD

**Issue by justinethier** [cyclone-scheme/winds#6]
Along the same lines as issue #5 it might be nice to record the version of cyclone used to compile a package during installation. That way if a new version of cyclone is installed, cyclone-winds could be instructed to upgrade/reinstall any installed packages so that they are rebuilt with the new version of the compiler.

This could be useful if there are breaking changes in a newer release.

**Comment by arthurmaciel** [comment]
I think that cyc-version on https://github.com/cyclone-scheme/cyclone-winds/blob/master/cyclone-winds.scm#L80 already is taking care of that, no?

**Comment by justinethier** [comment]
Thanks for the head's up @arthurmaciel . Let me take a closer look, hopefully later today. I need to spend more time understanding what is there now before trying to find a proper solution.

**Comment by arthurmaciel** [comment]
I appreciate the help @justinethier. If you have recommendations on whether to clarify the code, please let me know. Of course, feel free to change it in a way you find more clear or useful.

**Comment by justinethier** [comment]
Thanks @arthurmaciel . And you're absolutely right this data is already being tracked. No need for this ticket :)
